server:
  port: 8083
  serrver:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.204.156:3306/four_geek?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: mysql10010.
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/end/s2/nb/mapping/*.xml
  type-aliases-package: com.s2.nb.entity
